use starknet::ContractAddress;

// =============================================================================
// Interface: IQuantumGuardAccount
// =============================================================================
// External functions exposed by the smart wallet contract.

#[starknet::interface]
pub trait IQuantumGuardAccount<TContractState> {
    /// Submit proof commitment + transaction data for execution.
    /// The contract verifies:
    ///   1. The proof_commitment was generated by a trusted prover
    ///   2. The pubkey_hash matches the stored owner identity
    ///   3. The nonce is valid (replay protection)
    ///
    /// If all checks pass, the contract calls the target address.
    fn execute_with_proof(
        ref self: TContractState,
        to: ContractAddress,
        selector: felt252,
        calldata: Array<felt252>,
        proof_commitment: felt252,
        pubkey_hash: felt252,
        nonce: u64,
    ) -> bool;

    /// Get the owner's quantum public key hash (identity anchor).
    fn get_owner_pubkey_hash(self: @TContractState) -> felt252;

    /// Get the current transaction nonce.
    fn get_nonce(self: @TContractState) -> u64;

    /// Check if a prover address is whitelisted.
    fn is_approved_prover(self: @TContractState, prover: ContractAddress) -> bool;

    /// Add a new approved prover (owner-only).
    fn add_prover(ref self: TContractState, prover: ContractAddress);

    /// Remove an approved prover (owner-only).
    fn remove_prover(ref self: TContractState, prover: ContractAddress);

    /// Rotate the owner's quantum public key (owner-only).
    /// Used when generating a new ML-DSA keypair.
    fn rotate_owner_key(ref self: TContractState, new_pubkey_hash: felt252);
}

// =============================================================================
// Contract Implementation
// =============================================================================

#[starknet::contract]
pub mod QuantumGuardAccount {
    use super::IQuantumGuardAccount;
    use starknet::{ContractAddress, get_caller_address, get_contract_address, SyscallResultTrait};
    use starknet::syscalls::call_contract_syscall;
    use starknet::storage::{
        StoragePointerReadAccess, StoragePointerWriteAccess,
        Map, StorageMapReadAccess, StorageMapWriteAccess,
    };

    // ─── Storage ────────────────────────────────────────────────────

    #[storage]
    struct Storage {
        /// SHA-256 hash of the owner's ML-DSA-44 public key.
        /// This is the immutable identity anchor (until rotated).
        /// Stored as felt252 (first 31 bytes of the 32-byte hash).
        owner_pubkey_hash: felt252,

        /// Transaction nonce for replay protection.
        /// Incremented after each successful execution.
        tx_nonce: u64,

        /// Whitelisted prover addresses.
        /// Only proofs submitted by approved provers are accepted.
        approved_provers: Map<ContractAddress, bool>,

        /// Number of approved provers (for enumeration).
        prover_count: u32,
    }

    // ─── Events ─────────────────────────────────────────────────────

    #[event]
    #[derive(Drop, starknet::Event)]
    pub enum Event {
        TransactionExecuted: TransactionExecuted,
        ProverAdded: ProverAdded,
        ProverRemoved: ProverRemoved,
        OwnerKeyRotated: OwnerKeyRotated,
    }

    #[derive(Drop, starknet::Event)]
    pub struct TransactionExecuted {
        #[key]
        pub to: ContractAddress,
        pub nonce: u64,
        pub proof_commitment: felt252,
    }

    #[derive(Drop, starknet::Event)]
    pub struct ProverAdded {
        #[key]
        pub prover: ContractAddress,
    }

    #[derive(Drop, starknet::Event)]
    pub struct ProverRemoved {
        #[key]
        pub prover: ContractAddress,
    }

    #[derive(Drop, starknet::Event)]
    pub struct OwnerKeyRotated {
        pub old_hash: felt252,
        pub new_hash: felt252,
    }

    // ─── Constructor ────────────────────────────────────────────────

    #[constructor]
    fn constructor(
        ref self: ContractState,
        owner_pubkey_hash: felt252,
        initial_prover: ContractAddress,
    ) {
        // Store the owner's quantum identity
        self.owner_pubkey_hash.write(owner_pubkey_hash);
        self.tx_nonce.write(0);

        // Whitelist the initial prover
        self.approved_provers.write(initial_prover, true);
        self.prover_count.write(1);
    }

    // ─── External Implementation ────────────────────────────────────

    #[abi(embed_v0)]
    impl QuantumGuardAccountImpl of IQuantumGuardAccount<ContractState> {

        fn execute_with_proof(
            ref self: ContractState,
            to: ContractAddress,
            selector: felt252,
            calldata: Array<felt252>,
            proof_commitment: felt252,
            pubkey_hash: felt252,
            nonce: u64,
        ) -> bool {
            // 1. Verify caller is an approved prover
            let caller = get_caller_address();
            assert(self.approved_provers.read(caller), 'Caller not approved prover');

            // 2. Verify pubkey_hash matches owner
            let stored_hash = self.owner_pubkey_hash.read();
            assert(pubkey_hash == stored_hash, 'PubKey hash mismatch');

            // 3. Verify nonce (replay protection)
            let current_nonce = self.tx_nonce.read();
            assert(nonce == current_nonce, 'Invalid nonce');

            // 4. Verify proof_commitment is non-zero
            assert(proof_commitment != 0, 'Empty proof commitment');

            // 5. Increment nonce
            self.tx_nonce.write(current_nonce + 1);

            // 6. Emit event
            self.emit(TransactionExecuted {
                to: to,
                nonce: current_nonce,
                proof_commitment: proof_commitment,
            });

            // 7. Execute the downstream call (e.g. STRK transfer)
            let _retdata = call_contract_syscall(to, selector, calldata.span()).unwrap_syscall();

            true
        }

        fn get_owner_pubkey_hash(self: @ContractState) -> felt252 {
            self.owner_pubkey_hash.read()
        }

        fn get_nonce(self: @ContractState) -> u64 {
            self.tx_nonce.read()
        }

        fn is_approved_prover(self: @ContractState, prover: ContractAddress) -> bool {
            self.approved_provers.read(prover)
        }

        fn add_prover(ref self: ContractState, prover: ContractAddress) {
            // Only callable by the contract itself (i.e., via execute_with_proof)
            self._assert_only_self();
            self.approved_provers.write(prover, true);
            self.prover_count.write(self.prover_count.read() + 1);
            self.emit(ProverAdded { prover });
        }

        fn remove_prover(ref self: ContractState, prover: ContractAddress) {
            self._assert_only_self();
            self.approved_provers.write(prover, false);
            let current_count = self.prover_count.read();
            if current_count > 0 {
                self.prover_count.write(current_count - 1);
            }
            self.emit(ProverRemoved { prover });
        }

        fn rotate_owner_key(ref self: ContractState, new_pubkey_hash: felt252) {
            self._assert_only_self();
            let old = self.owner_pubkey_hash.read();
            self.owner_pubkey_hash.write(new_pubkey_hash);
            self.emit(OwnerKeyRotated {
                old_hash: old,
                new_hash: new_pubkey_hash,
            });
        }
    }

    // ─── Internal helpers ───────────────────────────────────────────

    #[generate_trait]
    impl InternalImpl of InternalTrait {
        /// Assert the caller is the contract itself.
        /// This ensures admin functions can only be called via execute_with_proof.
        fn _assert_only_self(self: @ContractState) {
            let caller = get_caller_address();
            let self_addr = get_contract_address();
            assert(caller == self_addr, 'Only self can call');
        }
    }

    // =============================================================================
    // Unit Tests (inside module so constructor + storage + impl are all visible)
    // =============================================================================

    #[cfg(test)]
    mod tests {
        use super::{IQuantumGuardAccount, QuantumGuardAccountImpl, InternalImpl};
        use super::{ContractState, contract_state_for_testing, constructor};
        use starknet::{ContractAddress, contract_address_const};
        use starknet::testing::{set_caller_address, set_contract_address};

        fn OWNER_HASH() -> felt252 {
            0x1a2b3c4d5e6f7890abcdef1234567890abcdef1234567890abcdef12345678
        }

        fn PROVER_ADDR() -> ContractAddress {
            contract_address_const::<0x100>()
        }

        fn OTHER_ADDR() -> ContractAddress {
            contract_address_const::<0x200>()
        }

        fn CONTRACT_ADDR() -> ContractAddress {
            contract_address_const::<0x999>()
        }

        fn deploy() -> ContractState {
            let mut state = contract_state_for_testing();
            constructor(ref state, OWNER_HASH(), PROVER_ADDR());
            state
        }

        // ─── Constructor ────────────────────────────────────────────

        #[test]
        fn test_constructor_sets_owner_hash() {
            let state = deploy();
            assert(QuantumGuardAccountImpl::get_owner_pubkey_hash(@state) == OWNER_HASH(), 'Owner hash mismatch');
        }

        #[test]
        fn test_constructor_sets_nonce_zero() {
            let state = deploy();
            assert(QuantumGuardAccountImpl::get_nonce(@state) == 0, 'Initial nonce should be 0');
        }

        #[test]
        fn test_constructor_whitelists_initial_prover() {
            let state = deploy();
            assert(QuantumGuardAccountImpl::is_approved_prover(@state, PROVER_ADDR()), 'Prover not whitelisted');
        }

        #[test]
        fn test_non_prover_not_whitelisted() {
            let state = deploy();
            assert(!QuantumGuardAccountImpl::is_approved_prover(@state, OTHER_ADDR()), 'Should not be prover');
        }

        // ─── Execute With Proof ─────────────────────────────────────

        #[test]
        fn test_execute_with_proof_success() {
            let mut state = deploy();
            set_caller_address(PROVER_ADDR());

            let result = QuantumGuardAccountImpl::execute_with_proof(
                ref state,
                contract_address_const::<0x300>(),
                0x1234,
                array![1, 2, 3],
                0xdeadbeef,
                OWNER_HASH(),
                0,
            );

            assert(result, 'Execute should return true');
            assert(QuantumGuardAccountImpl::get_nonce(@state) == 1, 'Nonce should be 1');
        }

        #[test]
        #[should_panic(expected: 'Caller not approved prover')]
        fn test_execute_rejects_non_prover() {
            let mut state = deploy();
            set_caller_address(OTHER_ADDR());

            QuantumGuardAccountImpl::execute_with_proof(
                ref state,
                contract_address_const::<0x300>(),
                0x1234,
                array![1, 2, 3],
                0xdeadbeef,
                OWNER_HASH(),
                0,
            );
        }

        #[test]
        #[should_panic(expected: 'PubKey hash mismatch')]
        fn test_execute_rejects_wrong_pubkey() {
            let mut state = deploy();
            set_caller_address(PROVER_ADDR());

            QuantumGuardAccountImpl::execute_with_proof(
                ref state,
                contract_address_const::<0x300>(),
                0x1234,
                array![1, 2, 3],
                0xdeadbeef,
                0xdeaddeaddeaddead,
                0,
            );
        }

        #[test]
        #[should_panic(expected: 'Invalid nonce')]
        fn test_execute_rejects_wrong_nonce() {
            let mut state = deploy();
            set_caller_address(PROVER_ADDR());

            QuantumGuardAccountImpl::execute_with_proof(
                ref state,
                contract_address_const::<0x300>(),
                0x1234,
                array![1, 2, 3],
                0xdeadbeef,
                OWNER_HASH(),
                5,
            );
        }

        #[test]
        #[should_panic(expected: 'Empty proof commitment')]
        fn test_execute_rejects_zero_proof() {
            let mut state = deploy();
            set_caller_address(PROVER_ADDR());

            QuantumGuardAccountImpl::execute_with_proof(
                ref state,
                contract_address_const::<0x300>(),
                0x1234,
                array![1, 2, 3],
                0,
                OWNER_HASH(),
                0,
            );
        }

        #[test]
        fn test_nonce_increments_sequentially() {
            let mut state = deploy();
            set_caller_address(PROVER_ADDR());
            let target = contract_address_const::<0x300>();

            QuantumGuardAccountImpl::execute_with_proof(
                ref state, target, 0x1, array![1], 0xaaa, OWNER_HASH(), 0,
            );
            assert(QuantumGuardAccountImpl::get_nonce(@state) == 1, 'Nonce != 1');

            QuantumGuardAccountImpl::execute_with_proof(
                ref state, target, 0x2, array![2], 0xbbb, OWNER_HASH(), 1,
            );
            assert(QuantumGuardAccountImpl::get_nonce(@state) == 2, 'Nonce != 2');

            QuantumGuardAccountImpl::execute_with_proof(
                ref state, target, 0x3, array![3], 0xccc, OWNER_HASH(), 2,
            );
            assert(QuantumGuardAccountImpl::get_nonce(@state) == 3, 'Nonce != 3');
        }

        // ─── Admin ──────────────────────────────────────────────────

        #[test]
        fn test_add_prover_by_self() {
            let mut state = deploy();
            let new_prover = contract_address_const::<0x400>();

            set_contract_address(CONTRACT_ADDR());
            set_caller_address(CONTRACT_ADDR());

            QuantumGuardAccountImpl::add_prover(ref state, new_prover);
            assert(QuantumGuardAccountImpl::is_approved_prover(@state, new_prover), 'New prover not approved');
        }

        #[test]
        #[should_panic(expected: 'Only self can call')]
        fn test_add_prover_external_fails() {
            let mut state = deploy();
            set_contract_address(CONTRACT_ADDR());
            set_caller_address(OTHER_ADDR());

            QuantumGuardAccountImpl::add_prover(ref state, contract_address_const::<0x400>());
        }

        #[test]
        fn test_remove_prover() {
            let mut state = deploy();
            set_contract_address(CONTRACT_ADDR());
            set_caller_address(CONTRACT_ADDR());

            QuantumGuardAccountImpl::remove_prover(ref state, PROVER_ADDR());
            assert(!QuantumGuardAccountImpl::is_approved_prover(@state, PROVER_ADDR()), 'Not removed');
        }

        #[test]
        fn test_rotate_owner_key() {
            let mut state = deploy();
            let new_hash: felt252 = 0xaabb00112233445566778899;

            set_contract_address(CONTRACT_ADDR());
            set_caller_address(CONTRACT_ADDR());

            QuantumGuardAccountImpl::rotate_owner_key(ref state, new_hash);
            assert(QuantumGuardAccountImpl::get_owner_pubkey_hash(@state) == new_hash, 'Key not rotated');
        }

        #[test]
        #[should_panic(expected: 'Only self can call')]
        fn test_rotate_key_external_fails() {
            let mut state = deploy();
            set_contract_address(CONTRACT_ADDR());
            set_caller_address(OTHER_ADDR());

            QuantumGuardAccountImpl::rotate_owner_key(ref state, 0xbad0bad0bad0);
        }
    }
}
