/// QuantumGuard Smart Account — Starknet Cairo Contracts
///
/// This package implements a quantum-resistant smart wallet using
/// Account Abstraction. Instead of verifying ECDSA signatures on-chain,
/// it accepts proof commitments generated by the off-chain Rust prover.
///
/// Architecture:
///   1. User signs transaction with ML-DSA-44 (off-chain, Python)
///   2. Rust prover verifies signature and generates SHA-256 commitment
///   3. This contract checks the commitment matches the stored identity
///   4. If valid, executes the transaction
///
/// Modules:
///   - quantum_account: Smart wallet with proof-based execution
///   - merkle_audit:    On-chain Merkle audit trail for transaction batches
///
/// Storage (quantum_account):
///   - owner_pubkey_hash: felt252  — SHA-256 of the ML-DSA public key (identity anchor)
///   - tx_nonce: u64               — Replay protection counter
///   - approved_provers: Map       — Whitelisted prover addresses
///
/// Storage (merkle_audit):
///   - batch_roots: Map            — batch_id -> Merkle root
///   - batch_tx_counts: Map        — batch_id -> transaction count
///   - approved_committers: Map    — Whitelisted batch committer addresses
///
/// Storage (account_factory):
///   - account_class_hash: ClassHash — Class hash of QuantumGuardAccount for deploys
///   - deployed_accounts: Map        — salt -> deployed contract address
///   - total_deployed: u32           — Total accounts deployed via factory

pub mod quantum_account;
pub mod merkle_audit;
pub mod account_factory;
